### ISSUE TITLE
Absorb the Phosphor Project

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/team-compass#28]
The Phosphor project has been archived by the author, and the name is no longer usable.  Here we propose to bring the existing code base as a new repository under the JupyterLab GitHub org, and give it a new name.  I say we give a week for folks to give suggestions on a new name.

**Comment by GordonSmith** [comment]
I would suggest using @jupyterlab/phosphor - While I suspect "phospor" can't be copyrighted, I would still seek written permission from @sccolbert first and if not given, then consider switching - but it is/was his baby and keeping the name will help preserve his legacy on the project.

I have a few housekeeping PRs I use on my fork which may be of interest:
* Add typescript types to published package
* UMD / es6 Support
* Updated to latest TS Compiler
* Use NPM instead of YARN (somewhat opinionated, but Yarn was masking some missing dependency issues between the projects)
* Removal of unofficial dom functions  (setImmediate / clearImmediate) 
* Some minor enhancements to the DockPanel
* etc.

Plus there is a whole ecosystem of visualizations which play well with the DockPanel (Shameless plug):  
* https://raw.githack.com/hpcc-systems/Visualization/master/demos/gallery/gallery.html?./samples/layout
* https://raw.githack.com/hpcc-systems/Visualization/master/demos/gallery/gallery.html

**Comment by bollwyvl** [comment]
Thanks for starting this discussion.

Good feature ideas, but I think with all the things in motion right now,
what we mostly need is clear, official messaging that Jupyter can provide
(even if we haven't done it yet):

- re-released packages of the dependencies in question of current lab heads
(presumably, 1.1.*, 1.2.*, 2.*) that downstreams can use confidently with
an identical API unburdened by the vague naming threat... We don't need to
sign up to support the entire back catalog

- a review/ci infrastructure ready to accept contributions and react to
them in a timely manner

- a readiness (indeed, enthusiasm) to respect the needs of other
contributing downstreams

- some tooling which can help with the transition

The worst things that could happen to lab adoption until all that is in
place is users and downstreams, due to fork FUD, rather than on a rational
assessment of the work and the investment it represents...

- stopping work
- starting more, private, or otherwise incompatible-for-no-reason forks of
the libraries in question or lab
- picking something else to base their work on
- not starting new work at all, hurting users

PR (ha) aside:

There are obvious advantages to moving all the libraries in question into
the jl/jl monorepo, and this can be done in a way that preserves history
while still respecting the wishes of all involved... e.g. git filter branch.

I hope we do maintain (therefore test) a hard separation of deps, though,
as allowing react/blueprint/d3/etc to infect the otherwise unopinionated
dependency tree would reduce its adoptability.

Because of the collisions with @jupyterlab (e.g coreutils), it seems we
need a namespace, irrespective of where it lives.

Ideally, something that is short, isn't too clever or derivative, on-brand,
without being too lab-centric might have the greatest chance of getting
outside contribution.

Haven't don't the brand/seo drive-though but perhaps some things like
@-on-npm:

- jupyterkit
- jupytoolkit
- jupytypes
- jupycore
- jupycleus
- jptk
- jpui
- jpyde
- jig

I dunno.

It may also be worth opening this up to the various mailing lists, which
get some more eyes.

I'd be happy help with the rebrand, once we get to that point, having done
some work on the OG stuff back in the day. We likely will still want
dedicated docs, examples, etc. but can be a bit more liberal with cross
linking to lab for examples, which may well be the only in-the-wild use of
a particular api.

**Comment by timkpaine** [comment]
I think its important to keep it as separate as possible, there are plenty of applications that rely on phosphor that don't want to pull in a bunch of jupyter-specific code.

**Comment by sccolbert** [comment]
@bollwyvl 

> vague naming threat

I made no such threats. Don’t libel me.

**Comment by bollwyvl** [comment]
No libel intended here! It is very clear in the third clause of the LICENSE that names of the contributors may not be used, but no extension is made to the name of the product, which the new README puts some **cannots** around. IANAL, but the language in the new README does not clearly grant use of already-published symbol tokens, in as-yet-unwritten source code which would share a name with the brand in question, are not somehow also covered under the language there, nor what action will be taken. It may well be that the name of the product is registered as a trademark. I haven't researched this further, since we're discussing how to cleanly rename to avoid any such problems by complying wit the wishes expressed there.

**Comment by sccolbert** [comment]
> No libel intended here

Then you should retract your statement which claims I made a threat, because I did not. 

Im more than happy to clarifying my meaning and work with the community on a statement which clarifies any ambiguities, but no one has yet asked me to so.

**Comment by timkpaine** [comment]
Please avoid antagonistic comments, @sccolbert's contributions to this project are extensive and appreciated, and any questions/comments about reasonings for archiving the project should be taking up individually.

**Comment by bollwyvl** [comment]
Sure, thanks for cleaning my comment up @timkpaine. We've all invested a lot in this work over the last _n_ years, and I'm personally grateful to everyone I've had the opportunity to work with during that time around the code.

Just trying to point out that a potential downstream would interpret the current guidance as a :red_circle: :tophat: -style-trademark-thing, rather than a BSD-conformance-thing, underlining the need to get something relatively official out soon which _fully complies_ with the guidance.

**Comment by ian-r-rose** [comment]
Here are few possible ideas on renaming/rebranding. I mostly went down a chemistry-related allusion hole, so take these as seriously/not-seriously as you like:

* Phosphate is a component of the mineral group **apatite**, which forms a major structural element of vertebrate skeletons.
* Phosphates form a structural part of DNA and RNA. Perhaps one of the nuclide bases could be a suitable name. Many of them have a sort of medicinal flavor to them, but I kind of like the idea of **adenine**.
* In a similar mineralogical vein: **monazite** is a phosphate mineral which is used by geochronologists to determine the age of various rocks. Perhaps not as nice of a metaphor, but a fun word.
* The Great Red Spot is a storm that has been storming on Jupiter (note the i) for centuries, and is big enough to swallow several Earths. We don't know for sure why it is red, but one theory involves photochemistry with phosphine. So something like **red spot** could be a nice name, with the downside that the connection could be proven incorrect with further data from the Juno mission.

**Comment by timkpaine** [comment]
@ian-r-rose i was thinking in the same vein, phosphor is an old name for phosphorus, so I was looking at other old chemical names.

Could also go for a moon https://en.m.wikipedia.org/wiki/Moons_of_Jupiter

**Comment by jasongrout** [comment]
More thoughts on the connection with light:

* lumenjs
* flourescent (hard to spell)

More elements close to it on the periodic table:

* xenon
* argon
* neonjs

**Comment by bollwyvl** [comment]
Picking something in the same group as would reflect compatibility:

> - nitrogen, n (taken)
- arsenic, as (taken)
- antimony, an (open)
  - used in batteries, 🔥 retardant, micro electronics
  - css classes would be funny, an-Widget
  - not in it for the mon(e)y
- bismuth (taken)
- moscovium (open but meh)

There are archaic forms of the above as well...

**Comment by telamonian** [comment]
"What's Jupiter made of?"

Roughly 90% hydrogen and 10% helium. So I would say we should hydrogen as the new name, but [someone](https://github.com/nteract/hydrogen) beat us to that...

**Comment by fperez** [comment]
@jasongrout already pointed out (we had this conversation elsewhere) that the name `candela` is already taken in npm, so it doesn't work. But I'm still going to write down the idea below just in case the direction of thinking is useful to someone to come up with another one... Naming is tricky and it's all about spurring ideas, so even ones that don't work can be useful :)  My original note follows:

In Colombia, 'fósforo' is both the element "phosphor" and the colloquial name for match (as in the little wooden sticks with flammable bit at the end), b/c the flammable tip of matches typically has a lot of phosphor in it (or used to, I have no idea how they're made today). And the name for a fluid lighter is --again colloquially-- "candela", which more precisely is a synonym for fire.

The "proper" Spanish words are cerilla (match) and encendedor (lighter), but in Colombia everybody uses fósforo and candela.

The word candela actually exists in English, it's the the SI unit for luminous intensity (meaning it's physical radiance but integrated with the human visual model of wavelength-dependent sensitivity).

**Comment by jasongrout** [comment]
Some more suggestions from our meeting today:

  - lumino
  - sol
  - solar
  - lightstick
  - glowstick
  - glow
  - lumo (esparanto)
  - lux (latin)
  - luce (italian)
  - marama (maori)

**Comment by jasongrout** [comment]
When we were discussing it, "lumino" kept coming back as a favorite. What do people think? (feel free to use thumbs up/down, or leave a comment for a nuanced response)

**Comment by jasongrout** [comment]
Also, someone suggested the proper Spanish word for "bright": luminosa

**Comment by tgeorgeux** [comment]
Lumino also comes from "Luminophore", which has two types, Phosphor and
Fluorophore. Kind of a cool callback to phosphor as well :)

https://en.wikipedia.org/wiki/Luminophore

**Comment by bollwyvl** [comment]
:+1: to `lumino`, but `@lumino` is taken on npm. Here's a [tool](https://npm.runkit.com/npm-name) for checking availability, since npm makes it kind of hard through the UI. Of the above, `@marama` is available. If we throw a `y` at some of them, it opens up a bit, and likely better SEO, anyhow. `lumyno` kinda sounds like a dynamo, which is cool.

**Comment by bollwyvl** [comment]
(sry, just didn't look hard enough, you can check by URL, e.g.  `https://www.npmjs.com/org/lumino`

**Comment by jasongrout** [comment]
> but `@lumino` is taken on npm.

By @blink1073, this morning :)

**Comment by choldgraf** [comment]
![](https://tse1.mm.bing.net/th?id=OGC.55b210f2ee572cbde57a547073867855&pid=Api&rurl=https%3a%2f%2fmedia.tenor.co%2fimages%2f55b210f2ee572cbde57a547073867855%2fraw&ehk=gCq5XcwGTnzrs6NfAEEHRO3kMk%2fmNIlRGHgsRKNE6DY%3d)

**Comment by tgeorgeux** [comment]
I am +1 on Lumino. Good looking out @blink1073 !

**Comment by jasongrout** [comment]
More bike-shedding: this is what the package list would look like:
```
@lumino/algorithm
@lumino/application
@lumino/collections
@lumino/commands
@lumino/coreutils
@lumino/datagrid
@lumino/datastore
@lumino/default-theme
@lumino/disposable
@lumino/domutils
@lumino/dragdrop
@lumino/keyboard
@lumino/messaging
@lumino/properties
@lumino/signaling
@lumino/virtualdom
@lumino/widgets
```

**Comment by bollwyvl** [comment]
:mountain_biking_man: :house: ed some [font ideas](https://nbviewer.jupyter.org/urls/gistcdn.githack.com/bollwyvl/5df9d06da8f9a74af6fb9cb1c852d1c8/raw/31a2a1a3c71f3e51368e31a64f0de7ffa31dde11/lumino-font-concepts.ipynb)

>  it's nice that https://raw.githack.com is picking up for rawgit... i got 503ed vs the mothership

some criteria:
- open source (OFL or equivalent)
- has an `l` that doesn't look like a `1`, or just look cool

On individual fonts:
- I particularly like the interplay between the serifs on Flamenco: those could be expanded into boxes suggesting dockpanel

**Comment by bollwyvl** [comment]
As for the inhabitants of the bikeshed:

I'd love to bring in a [jo](https://docs.google.com/presentation/d/1sh1LEze9wPrSuwzbCeLy0US8Fe3t2xD9ZNwlLvjSD4A/)-like treatment for this... unsurprisingly lu. Lu's probably a bit more boxy than jo, maybe a little more transforming-pet-like, and helps jo get things done. I can imagine a team of lus:

- delivering messages
- sending signals 
- interacting with algorithms
- shopping at the data store
- playing hide-and-seek/brady-bunch/hollywood-squares in a datagrid
- plugging together apps
- typing on a keyboard like ghost in the shell
- dragging/dropping around DOM with a claw game
- looking at virtual DOM in a visor
- listening for properties
- disposing of stuff (responsibly)
- painting with a command palette

**Comment by bollwyvl** [comment]
When rebooting the docs, it would perhaps be a good time to revisit [sphinx-js](https://github.com/mozilla/sphinx-js#typescript-support) for the autogenerated parts, which should likely be considered for lab as well.

Also, it would be very interesting to make a mini-[jyve](https://deathbeds.github.io/jyve) for dogfooding the docs with interactive examples... might as well go ahead and ship the typescript interepreter, which basically has all the nuts and bolts for a language server experience, especially with monaco.

**Comment by JohanMabille** [comment]
+1 on Lumino.

**Comment by blink1073** [comment]
I think the consensus if for `lumino`.  I'll give this another 24 hrs for anyone to disagree and then go ahead and start the migration.  Cheers!

**Comment by jasongrout** [comment]
> I think the consensus if for `lumino`. I'll give this another 24 hrs for anyone to disagree and then go ahead and start the migration. Cheers!

Sounds good to me. +1.

**Comment by jasongrout** [comment]
IIRC, we were going to release packages with exactly the same commit as the last released phosphor packages to make the transition for anyone literally a name change (with no code changes)?

**Comment by blink1073** [comment]
Yes, that sounds right

**Comment by blink1073** [comment]
I created the [repo](https://github.com/jupyterlab/lumino) and made a release of all packages.  I did the following:

- Updated naming, contributing guidelines, and licensing
- Removed auto-generate docs for now - I think we should target RTD

**Comment by vidartf** [comment]
@blink1073 Thanks for handling the logistics here! Would you now say that the process is completed, or are there any remaining tasks?

**Comment by blink1073** [comment]
Sounds good, I created https://github.com/jupyterlab/jupyterlab/issues/7534 to track the rest of the transition.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/is-phosphorjs-no-longer-supported/3451/2
