### ISSUE TITLE
Where to upload permanent design assets?

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/team-compass#62]
We have a lot of design assets for JupyterLab that are living across different places (Google Drive, Dropbox, Figma, Etc..) I want a place to let these all live on Github without having to link out to other places. 

I was thinking of making a Repo JupyterLab/Design. I don't know if we would treat this the same way we treat other more product-based repos as I don't plan to house any actual software in it, only reference. 

Let me know what you all think!

**Comment by tgeorgeux** [comment]
As a follow up from yesterday's meeting, I will open a repo. The point of the repo at this point is to have a parking lot for design assets that may be relevant in the future for different problems that arise. We're going to work towards documenting design practices in the JupyterLab Documentation.

I do think a folder within the team-compas would also be a reasonable place to hold these, if that is preferred, please ring in here.

**Comment by choldgraf** [comment]
FWIW jupyterhub has its own design repo as well: https://github.com/jupyterhub/design

we use that in combination with a Google slides presentation that has a lot of logos in various configurations in it, because it's much easier for everyone to edit: https://docs.google.com/presentation/d/11Ag7oj8zaRbbTSLFTMYEAP-7WWCLFJRkKaEjjjE-nSA/edit#slide=id.p
