### ISSUE TITLE
JupyterLab rc release sprint tomorrow

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/team-compass#94]
I would like to propose that we setup a working call on Zoom tomorrow afternoon for folks to work together on getting the rc out the door. I can start as early as 12:30pm PT. Does that work for other folks interested in helping to cut the release?

**Comment by echarles** [comment]
Thx @ellisonbg for organising this. Unfortunately, my week is too busy so I will not be able to help here.

I think @goanpeca has tried the cookie-cutter and he said he had some issues with it. I don't know if that issue is linked to jupyterlab or to the cookie-cutter, but thought useful too mention it to double-check if it has to be considered in the release plan.

**Comment by vidartf** [comment]
Closing this since the date has passed 👍
